# Generated by Django 5.2.7 on 2025-10-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network'), ('access', 'Access & Security'), ('general', 'General Inquiry'), ('acc', 'ACC'), ('dialpad', 'Dialpad'), ('hubspot', 'Hubspot'), ('google', 'Google Workspace'), ('apple', 'Mac Issues'), ('windows', 'Windows Issues'), ('microsoft', 'O365 Issues'), ('sap', 'SAP Errors')], default='general', max_length=22),
        ),
    ]
