# Generated by Django 5.2.7 on 2025-10-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_attachment_file_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
