# Generated by Django 5.2.7 on 2025-10-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_attachment_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
