# Generated by Django 5.2.7 on 2025-10-15 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Critical, High, Medium, Low', max_length=100)),
                ('quadrant', models.CharField(choices=[('do_first', 'Do First (Urgent & Important)'), ('schedule', 'Schedule (Important & Not Urgent)'), ('delegate', 'Queue (Urgent & Not Important)'), ('delete', 'Backlog / Archive (Not Urgent & Not Important)')], max_length=10, unique=True)),
                ('resolution_time', models.DurationField(default=datetime.timedelta(days=1), help_text="Enter a duration, e.g., '3 days', '8 hours', or '1 day 12 hours'.")),
            ],
        ),
    ]
