# Generated by Django 5.2.7 on 2025-10-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_completed_at_task_paused_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slapolicy',
            name='quadrant',
            field=models.CharField(choices=[('do_first', 'Do First (Urgent & Important)'), ('schedule', 'Schedule (Important & Not Urgent)'), ('queue', 'Queue (Urgent & Not Important)'), ('backlog', 'Backlog / Archive (Not Urgent & Not Important)')], max_length=10, unique=True),
        ),
    ]
